spring:
  application:
    name: product-api
  profiles:
    default: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:product_db}?serverTimezone=UTC
    username: ${DB_USER:product_db}
    password: ${DB_PASSWORD:localdb}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:4200}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
